[package]
name = "flow-state"
version = "0.2.0"
edition = "2024"
description = "A fitting and predicting module to expose conn.log features as cluster of behaviour for markov chain transition prediction"
license = "MIT"

[dependencies]
indexmap = "2.14.0"
linfa = "0.8.1"
linfa-clustering = "0.8.1"
linfa-nn = "0.8.1"
ndarray = "0.16"
rand_xoshiro = "0.6"
